version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 60
      runas: root
    - location: systemctl start flask.service
      timeout: 10
      runas: root
  AfterInstall:
    - location: /usr/bin/systemctl enable /var/www/config/flask.service
      timeout: 10
      runas: root
  ApplicationStart:
    - location: /usr/bin/systemctl start flask.service
      timeout: 10
      runas: root
  ApplicationStop:
    - location: /usr/bin/systemctl stop flask.service
      timeout: 10
      runas: root
