version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/install_requirements
      timeout: 10
      runas: root
    - location: scripts/enable_service
      timeout: 10
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 10
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 10
      runas: root
