#!/bin/sh

echo "Enabling services..."

echo "  Enabling nginx service..."
/usr/bin/systemctl enable nginx.service

echo "  Enabling Hello World service..."
/usr/bin/systemctl enable /var/www/config/helloworld.service

echo "Services enabled!"
