#!/bin/sh

echo "Installing system packages..."

echo "  Installing Python..."
/usr/bin/yum install -y -q python3-pip python3-devel python3-wheel

echo "  Installing nginx..."
/usr/bin/amazon-linux-extras install -y -q nginx1.12

echo "  Removing nginx config file (if it exists)..."
/bin/rm /etc/nginx/nginx.conf

echo "Done installing system packages!"
