#!/bin/sh

echo "Installing system packages..."
/usr/bin/yum install -y -q python3-pip python3-devel python3-wheel

echo "Installing pip dependencies..."
/usr/bin/pip3 install -r /var/www/requirements.txt